"""THE KNOWN-GAPS LEDGER - everything the tool knowingly does not know, in ONE place.

Joel, 2026-08-10: "our main encounter of new bugs are based on not having
knowledge about everything in-game... having only detailed knowledge when one
person brings up one bug is not really being well thought out."

The knowledge exists but was scattered: every reality check pins its own open
gaps, the mode-tags table classifies every gate, and the ruling-class items
live in CLAUDE.md. This tool compiles them into docs/KNOWN-GAPS.md so that:
  1. every NEW field report is triaged against the ledger FIRST - "known gap"
     and "genuinely new" are different work;
  2. proactive work picks from the ledger instead of waiting for a report;
  3. nothing gets forgotten in the rush of an update.

The generated sections pull LIVE from the instruments (they cannot go stale
without this file noticing); the curated sections cite their CLAUDE.md ruling.
Usage: python tools/gap_ledger.py [--check]   (--check fails if the doc is stale)
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
sys.path.insert(0, os.path.join(ROOT, "server"))
OUT = os.path.join(ROOT, "docs", "KNOWN-GAPS.md")


def build():
    from reality_check_effect_coverage import OPEN_GAPS      # noqa: E402
    from mode_tags import TAGS                               # noqa: E402
    import first_principles as fp                            # noqa: E402

    L = []
    L.append("# Known gaps - what the tool knowingly does not know yet")
    L.append("")
    L.append(f"Generated by `tools/gap_ledger.py` at model v{fp.MODEL_VERSION}. "
             "Do not edit by hand; regenerate. **Triage every new field report "
             "against this ledger first** - a report matching a known gap "
             "confirms priority; one matching nothing is genuinely new "
             "knowledge and belongs in an instrument before it belongs in a fix.")
    L.append("")

    L.append("## Data gaps, pinned by the coverage check (fails if any drifts)")
    L.append("")
    L.append("| effect | aspect | side | powers | state |")
    L.append("|---|---|---|---|---|")
    for (eff, asp, side), (count, why) in sorted(OPEN_GAPS.items()):
        first = why.split(". ")[0].replace("|", "/")
        L.append(f"| {eff} | {asp} | {side} | {count} | {first} |")
    L.append("")

    L.append("## Mode and meter gates, classified (mode-tags check, fails both ways)")
    L.append("")
    by_class = {}
    for tag, (cls, why) in TAGS.items():
        by_class.setdefault(cls, []).append(tag)
    order = {"SCENARIO": "blocked on one scenario input (the ruling class)",
             "PROB": "stated chances - weighted where landed (crits took the floor)",
             "MODE": "duty cycle derivable from the game's own numbers",
             "DERIVED": "derived elsewhere; taking the rows would double-count",
             "LABEL": "not gates at all - the client naming a power's own effect"}
    for cls, desc in order.items():
        tags = sorted(by_class.get(cls, []))
        L.append(f"- **{cls}** ({len(tags)}): {desc}. {', '.join(tags)}")
    L.append("")

    L.append("## Blocked on one ruling or one number (each cites its CLAUDE.md entry)")
    L.append("")
    for item in [
        "**mez_in** - one number ('how often does content mez you') unblocks "
        "~289 powers scoring nothing today: self mez protection (landed, "
        "inert), ally mez protection and resistance (Clear Mind, Clarity, "
        "Thaw...), and the debuff-resistance families. The single "
        "highest-leverage open ruling.",
        "**Spawn rank mix** - minion/lieutenant/boss shares at typical "
        "settings. Unlocks the crit premium above the 5% floor and would "
        "sharpen rank-dependent accuracy terms.",
        "**Operating health** - the 13 health-scaling powers (SR scaling "
        "resistance, Gamma Boost) are decoded and pinned; a linear curve's "
        "honest average is its midpoint, so 50% is the derived recommendation.",
        "**Stack meters** - BuildStatic, BuildFrenzy, Contaminated, "
        "Disintegrate, the combo systems, Bio's stance: one scenario constant "
        "each, or one ruling for the class. Titan Weapons' Momentum is this "
        "class too: Whirling Smash and Follow Through are usable ONLY inside "
        "the Momentum window (client short help 'Requires Momentum'; v46 "
        "zeroes them for AFK), so active TW farming pays a structural tax - "
        "the set cannot chain high-cap AoEs freely (Maelwys, topic 64761). "
        "Pricing the fast-form uptime + the gate for ACTIVE play is the "
        "remaining piece.",
        "**The +5x8 AFK tier** - Maelwys: +5x8 (50+1 vs 55 in AE) is the real "
        "ceiling players farm at and both Fiery Aura builds can pass it with "
        "fully passive builds. Our sustain ladder stops at +4x8; extending it "
        "needs the +5 enemy accuracy/DPS numbers for the scenario table.",
        "**Stone Armor farm candidate** - passively caps res+def with Rooted "
        "regen, Brimstone damage procs and Minerals recharge (Maelwys's "
        "RadM/Stone example: 49 HP/s passive, Atom Smasher auto-fire). "
        "Blocked on the aura/patch proc valuation ruling; certify a Stone "
        "Armor alternative when that lands.",
        "**Regen model: VERIFIED CORRECT end to end** (2026-08-17, retraction "
        "of the same-day 'under-captured' alarm - both supporting probes were "
        "bad: a phantom piece uid slotting nothing, then a wrong-keyed "
        "census). tools/census_power_regen.py is the standing instrument: 146 "
        "client self-regen records in served sets, 125 carried, 21 gaps all "
        "known classes (Gamma Boost health-scaling ruling x5; alias/liveness "
        "records like Rime and Reactive Regeneration to cross-check against "
        "the missing-powers pins - never blind-add). Maelwys's RadM/Stone "
        "example measures +4x8 FULLY PASSIVE (37.7 HP/s) at contribution "
        "199.7 in OUR model via the faithful converter "
        "(coh-scorer-lab/measure_maelwys.py) - the tier-vs-objective "
        "ruling's live exhibit, no model work prerequisite after all.",
        "**AFK offense is unmodelled** (Maelwys 2026-08-16, confirmed in our "
        "artifacts): the farm_afk SUSTAIN ledger correctly allows regen + ONE "
        "non-interruptible auto-fire power, but the OFFENSE channel still "
        "prices the full click attack chain an AFK farmer cannot cast - the "
        "TW/Bio champion certified on Fire Ball/Char clicks and skipped Bio's "
        "damage aura. An AFK damage rule (damage auras + the one auto-fire + "
        "procs only) is a model change and a farm re-cert; Joel's ruling.",
        "**Domination's magnitude half** - adds or replaces is ambiguous in "
        "the client (3 of 41 pairs fit neither reading). Duration half is "
        "shipped; magnitude deliberately not guessed.",
        "**Fiery Embrace's type question** - the client grants a FIRE-typed "
        "buff; our damage_buff is type-blind. Measure before touching; adding "
        "the Fire templates first is the known inflation trap.",
        "**The ally channel** - ally mez, ally absorb, ally slow resistance "
        "share one unbuilt channel; build it once when mez_in lands.",
        "**Fighting-pool cross-boost** - Boxing/Kick/Cross Punch each stronger "
        "for owning the others; real, named, unmodelled.",
        "**Power Boost's Set_Mode** - a 15-second amplifier mode, the same "
        "capability class as Fury; roster known via tags, uptime is the gap.",
        "**~460 target-cap/radius rows** - client disagreements never "
        "classified; blanket-sync is known-wrong (pseudo-pet folds), so each "
        "needs adjudication.",
    ]:
        L.append(f"- {item}")
    L.append("")

    L.append("## Needs eyes in the game (one look each)")
    L.append("")
    for item in [
        "**/thumbtack** - paste one copied badge command in its zone; watch "
        "where the X lands. Publicly stated as untested.",
        "**Iron Man / Adamant accolade** - does holding the badge grant "
        "+10% HP / +10 end on Homecoming? A character sheet answers it.",
        "**Unrelenting Fury stack cap** - template says 2, help text says 5; "
        "the stack counter in a fight settles 1.5pp of regen.",
        "**Fury's third attack** - a farm log from a Brute with 3+ "
        "single-target attacks turns the Fury fit from fitting into measuring.",
        "**Domination magnitude** - mez a +1 boss with and without Domination "
        "up; landing or not distinguishes adds-vs-replaces.",
    ]:
        L.append(f"- {item}")
    L.append("")

    L.append("## Unknowable from the client (server-side on Homecoming)")
    L.append("")
    for item in [
        "Zone level ranges, TF rosters and gates, exploration coordinates "
        "(the i24 archive torrent is the sanctioned route).",
        "The one-origin-pool rule (enforced from convention; no requires "
        "expression carries it).",
        "Content liveness itself - the bins prove mechanics, not release; "
        "the liveness gate pins data to the shipped Mids-derived snapshot.",
        "Whether Mids' PvP-only constants (the 5.33x heal conversions) match "
        "live PvP - inert in PvE either way.",
    ]:
        L.append(f"- {item}")
    L.append("")
    return "\n".join(L) + "\n"


def main():
    text = build()
    if "--check" in sys.argv:
        cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if cur != text:
            print("gap_ledger: docs/KNOWN-GAPS.md is STALE - regenerate with "
                  "python tools/gap_ledger.py")
            sys.exit(1)
        print("gap_ledger: docs/KNOWN-GAPS.md is current")
        return
    open(OUT, "w", encoding="utf-8", newline="\n").write(text)
    print(f"wrote {OUT} ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
