"""Windows version resource for the frozen exes (Properties -> Details).

Both specs shipped exes with a BLANK Details tab — no file version, no
publisher, no description (noticed 2026-09-02, fixed 2026-09-19). Blank
properties look like malware-ish anonymity to users and to AV heuristics, and
Task Manager shows nothing useful next to the process.

The resource is GENERATED at build time from the same version string the app
itself reports, so it can never drift from VERSION / LITE_VERSION the way a
hand-maintained version_info.txt would. Written next to the spec and
gitignored, like build_commit.txt.
"""

COMPANY = "Pulsekin (joelc67)"          # matches installer/HeroCompanion.iss AppPublisher
COPYRIGHT = "Copyright (c) 2026 Pulsekin (joelc67)"

_TEMPLATE = """# GENERATED by tools/version_res.py at build time — do not edit, do not commit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={vers}, prodvers={vers},
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('040904B0', [
      StringStruct('CompanyName', {company!r}),
      StringStruct('FileDescription', {description!r}),
      StringStruct('FileVersion', {version!r}),
      StringStruct('InternalName', {name!r}),
      StringStruct('LegalCopyright', {copyright!r}),
      StringStruct('OriginalFilename', {filename!r}),
      StringStruct('ProductName', {product!r}),
      StringStruct('ProductVersion', {version!r})])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def _tuple(version):
    """'0.12.49' -> (0, 12, 49, 0). Windows wants exactly four integers."""
    parts = [int(p) for p in version.strip().split(".")]
    if not parts or len(parts) > 4:
        raise ValueError(f"unusable version string: {version!r}")
    return tuple((parts + [0, 0, 0, 0])[:4])


def write_version_file(path, version, name, description, product=None):
    """Write a PyInstaller version-info file; returns `path` for EXE(version=...)."""
    with open(path, "w", encoding="utf-8") as f:
        f.write(_TEMPLATE.format(vers=_tuple(version), version=version.strip(),
                                 name=name, filename=f"{name}.exe",
                                 description=description, product=product or description,
                                 company=COMPANY, copyright=COPYRIGHT))
    return path


if __name__ == "__main__":
    assert _tuple("0.12.49") == (0, 12, 49, 0)
    assert _tuple("0.1.18") == (0, 1, 18, 0)
    assert _tuple("1") == (1, 0, 0, 0)
    for bad in ("", "1.2.3.4.5", "0.12.x"):
        try:
            _tuple(bad)
        except ValueError:
            pass
        else:
            raise AssertionError(f"{bad!r} should have been rejected")
    import tempfile, os
    p = os.path.join(tempfile.mkdtemp(), "v.txt")
    body = open(write_version_file(p, "0.12.49", "HeroCompanion", "Hero Companion"),
                encoding="utf-8").read()
    assert "filevers=(0, 12, 49, 0)" in body and "'0.12.49'" in body, body
    assert "'HeroCompanion.exe'" in body, body
    compile(body, p, "eval")          # PyInstaller parses this file as one expression
    print("version_res self-check: OK")
